### PR TITLE
Add  `createEnumType` action to schema methods

### PR DESCRIPTION
**Pull request by thetre97**

### CODE REVIEW

**Comment by hjvedvik** [comment]
Oh, must have forgotten that one. Thanks :)

**Comment by thetre97** [comment]
Thanks @hjvedvik - Could I ask when the next version will be released with this patch?

**Comment by hjvedvik** [comment]
Published a new version now :)

**Comment by thetre97** [comment]
Thank you! Just about to release a shopify source plugin.

**Pull request merged**
