### PR TITLE
source-drupal: Retain "meta" object when creating references

### PR DESCRIPTION
**Pull request by matt-e-king**

### CODE REVIEW

**Comment by matt-e-king** [comment]
I can make sure to update the Drupal Starter and the README to announce the breaking change if in fact, this is the route we want to take. Thanks!

**Comment by hjvedvik** [comment]
Thanks, @matt-e-king. I can't think of any other way to do this, so it looks good to me :)

**Comment by matt-e-king** [comment]
Great, @hjvedvik! Do you have a preference on how to document this breaking change in the [README](https://github.com/gridsome/gridsome/tree/master/packages/source-drupal)? Or should we start a change log?

And do you handle the version bumping on your end? If yes, what version will this change to?

**Comment by hjvedvik** [comment]
@matt-e-king The changelog, version number, and tag are generated automatically. And because we are in the 0.x stages, I'll just merge this PR as a feature which bumps it up to 0.3 :)

**Comment by matt-e-king** [comment]
Cool, thanks @hjvedvik - I committed changes to the README. Feedback is welcome :)

**Comment by hjvedvik** [comment]
Looks good @matt-e-king :) Do you have any thoughts about this change @tanc?

**Comment by tanc** [comment]
This looks like a good approach. I probably won't have time to test it properly as I'm on holiday for a few weeks. Thanks for the good work!

**Pull request merged**
