### PR TITLE
cli/update-notifier: 4.1.0

### PR DESCRIPTION
**Pull request by dargmuesli**
Should fix https://app.snyk.io/vuln/SNYK-JS-DOTPROP-543489.

### CODE REVIEW

**Comment by hjvedvik** [comment]
Thanks, @dargmuesli. `optimize-css-assets-webpack-plugin`, `lerna` and `conventional-changelog` also has a deep dependency of an older `dot-prop` version. `conventional-changelog` might be good after https://github.com/stevemao/compare-func/pull/3 has been merged. But I can't find any PR's for the two other packages (`postcss-selector-parser` and `@lerna/project`).

**Comment by dargmuesli** [comment]
Ok, but this PR would fix the issue for the cli package, wouldn't it?

**Comment by hjvedvik** [comment]
Yes, it will :)

**Comment by dargmuesli** [comment]
🎉 thank you!

**Pull request merged**
