### PR TITLE
re-add circle ci configuration

### PR DESCRIPTION
**Pull request by dev23jjl**
This pull request is to re-add the Circle CI configuration so that the Circle CI tests can run and therefore pull requests can pass and be merged.

### CODE REVIEW

**Comment by dev23jjl** [comment]
Is it possible that the devs no longer are using Circle CI, if so they should remove Circle CI from the checks that are not being used. The only reason that I am suggesting this because I ran Circle CI from the fork, and it came up with this error:

`yarn install v1.22.4`
`[1/5] Validating package.json...`
`[2/5] Resolving packages...`
`[3/5] Fetching packages...`
`info fsevents@1.2.13: The platform "linux" is incompatible with this module.`
`info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.`
`error graphql@16.0.1: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.16.0 || >=16.0.0". Got "12.16.2"`
`error Found incompatible module.`
`info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

`Exited with code exit status 1`
`CircleCI received exit code 1`

I used the config file from the v0.7.23 release's source code. Does anyone at @gridsome know? If so, I'll just close this pull request. Otherwise, I'm not sure what to do.

**Comment by dev23jjl** [comment]
I think that I'll just close this, Gitpod added a .yml file (_annoying_) and I don't really think it's all that necessary.

**Comment by hjvedvik** [comment]
I've removed the CircleCI checks now :) We moved the tests over to GitHub actions a while ago but forgot to update the branch settings.

**Comment by dev23jjl** [comment]
Thanks, @hjvedvik. I guess I'll just delete the branch that I made.

**Pull request closed without merging**
