### PR TITLE
normalize 'Custom Endpoint' fields prior to injection

### PR DESCRIPTION
**Pull request by earlman**
I was trying to take advantage the latest update for custom endpoints to create Gridsome Collections based on a specific WP endpoint. (because there's no support yet for filtering the WP posts I want to use). I was trying to query `route: "/wp/v2/posts?categories=251"` but it was giving me an error. From the source code it seems like you ran into the same one, hence the "normalizeFields" function. I implemented it into the getCustomEndpoints function and it works great!

### CODE REVIEW

**Comment by earlman** [comment]
My apologies. I'm quite new to creating pull requests (this is only my second). I made a mistake in the most recent commit. I changed the package name to use it in my project, but I didn't realize I committed it to this PR. Not quite sure how to get rid of that 😅

**Comment by hjvedvik** [comment]
No problem @earlman, just correct the package name and commit again :) And thanks for the PR! I will try to review it tomorrow :)

**Comment by earlman** [comment]
Lol duh.

Also, no problemo. Hopefully it's helpful

**Comment by hjvedvik** [comment]
This looks okay to me, but I haven't tested in a real project. What do you think @jamacon36? The `normalizeFields` method converts fields with posts to references and extracts `rendered` values. Or should each custom endpoint have a `normalize` option?

**Comment by jamacon36** [comment]
@hjvedvik @earlman yeah a `normalize` option feels like the way to go since it's less opinionated and provides for things like menus and taxonomies that don't necessarily need refs created

**Comment by earlman** [comment]
mm ok sounds good. ill try to put something in in the next few days.

**Comment by jamacon36** [comment]
hey @earlman any news? It'd be cool to use the feature :)

**Comment by earlman** [comment]
Oops, got distracted while I was working on it earlier and never got back to it. Thanks for the reminder.

How's that? This looks for `normalize: true` in the customEndpoint object before running the function

**Comment by jamacon36** [comment]
Looks good! Thoughts @hjvedvik ?

**Comment by hjvedvik** [comment]
Looks good to me too. Thanks, @earlman :)

**Comment by earlman** [comment]
🎉🎉🎉

**Pull request merged**
