### PR TITLE
Allow index.html template to be overridden

### PR DESCRIPTION
**Pull request by K3TH3R**
This small PR basically allows someone to add an `index.html` to their `/src` directory and override the default template. It's probably not going to happen very often, but it's the easiest way to allow people to add CDN/external scripts to the footer of their site.

### CODE REVIEW

**Comment by hjvedvik** [comment]
Thanks! Will be great to have the posibillity to override the default template. We'll include this in the next release :)

**Comment by physcocode** [comment]
+1

**Comment by tomtev** [comment]
This is great! Could you also create documentation for it on gridsome.org?

**Comment by K3TH3R** [comment]
@tomtev Absolutely. Is there a page you would prefer it added to or should I create a new page in the sidebar? I'm thinking maybe "Overriding Index.html" as an item right below "body & html attributes"?

**Comment by K3TH3R** [comment]
Documentation for this added to my existing documentation PR

**Pull request merged**
