### PR TITLE
feat(webpack): make it possible to add enviroment variables

### LINKED ISSUE #88: Environment variables
We should be able to specify environment specific variables that will be available in Vue components? May be something like `development.env` and `production.env` in the root of a project?

### PR DESCRIPTION
**Pull request by isoppp**
fix #88 and #58 

Code and specification referenced Nuxt.js ([doc](https://nuxtjs.org/api/configuration-env/)).

## Description

- Add `env` config to `gridsome.config.js`
- Make it possible to access these configs in Vue

- Attach environment variables start with `GRIDSOME_ENV` to `process.env`

- Add `process.env.NODE_ENV` and `process.isProduction` to base env config.

---

If need document, I will try to create it after review.

### CODE REVIEW

**Comment by hjvedvik** [comment]
Thanks, this will be a nice feature :)

I think we can just let the env prefix be `GRIDSOME_` since they already are environment variables. And what do you think about including the `dotenv` package to support `.env` files too?

The `develop` command adds `SOCKJS_ENDPOINT`, `GRAPHQL_ENDPOINT` and `GRAPHQL_WS_ENDPOINT` as global variables through the webpack define plugin. But it would be better to add them to `process.env` and let people override them somehow. Specially for this use case #58.

**Comment by isoppp** [comment]
Thank you for confirmation :D

I tried to fix those issue.

- Change the name prefix form GRIDSOME_ENV to GRIDSOME_.

- Add dotenv package support.

But perhaps it may confuse some users, because it's difficult to merge `dotenv` and `config.env` when it register webpack.
For example, `SOCKJS_ENDPOINT` etc added this time can be overwritten from `gridsome.config.env`, but from `.env` it can not overwrite.
If you want to avoid this confusion it may be better to detach dotenv as a plugin or need some good idea.

- Make it possible to specify dev endpoints

**Comment by hjvedvik** [comment]
Great work! Yes, it's probably a good idea to just use `dotenv.parse` directly so you have more control. And would it be an idea to parse and merge with `process.env` before `gridsome.config.js` is loaded in `app/loadConfig.js`? That will probably make the `env` config unnecessary since the `GRIDSOME_*` plus the `develop` variables can be added to webpack automatically and `process.env` has all the other variables in Node.js. Or what do you think?

#### Example usage:

```
// .env
GRIDSOME_API_URL=https://api.example.com
API_KEY=1234567890

// gridsome.config.js
module.exports = {
  plugins: [
    {
      use: 'gridsome-source-plugin',
      options: {
        apiKey: process.env.API_KEY
      }
    }
  ]
}

// src/pages/Index.vue
export default (
  async mounted () {
    const res = await axios.get(process.env.GRIDSOME_API_URL)
  }
}
```

**Comment by isoppp** [comment]
wow, nice idea! :D
I fixed it!

And, made it possible switch env file by NODE_ENV.
(.env.development and .env.production)

Please confirm again :)

**Comment by hjvedvik** [comment]
Looks good :) Just a few thoughts; Use `context` instead of `process.cwd()`. We should also fallback to `.env` if no `.env.${env}` file exists. And maybe it is better to use `Object.assign(process.env, parsed)` to keep the original reference to `process.env`.

**Comment by isoppp** [comment]
Thank you for confirmation! I fixed those issues :)

**Comment by isoppp** [comment]
above commit resolved conflicts

**Comment by arttemiuss43** [comment]
I can't make it work. I add `.env` file in the root of a project with content `GRIDSOME_API_URL=http://localhost`. Then when I use it in component like `process.env.GRIDSOME_API_URL` it returns undefined. I also tried to add environment variables in env config in gridsome.config.js and add environment based env files like `.env.development`. Nothing works. It only works when I use following in gridsome.config.js:

```
if (process.env.NODE_ENV === 'production') {
    require('dotenv').config({ path: '.env.production' })
} else {
    require('dotenv').config({ path: '.env' })
}

module.exports = {
    chainWebpack: config => {
        config
            .plugin('env')
            .use(require.resolve('webpack/lib/EnvironmentPlugin'), ['GRIDSOME_API_URL'])
    },
}
```

What am I doing wrong?

**Comment by isoppp** [comment]
@arttemiuss43
This PR was merged, but didn't released yet.
Are you using master branch of this repository directly?
If you aren't using, this PR probably will include on v0.5.

And that feature don't need config.
You put `.env` or `.env.{mode}` file only then it's should work.

**Comment by arttemiuss43** [comment]
Thank you for clarification. No, I don't. I just add gridsome as usual package using yarn.

**Comment by isoppp** [comment]
@arttemiuss43 
Also, I tried your code, it's worked.

steps to reproduce:

1. exec `gridsome create xxx`
2. add `.env` file to root dir
```
GRIDSOME_API_URL=example
```
3. `yarn add dotenv`
4. add code writing above to gridsome.config.js
5. add `console.log(process.env.GRIDSOME_API_URL)` to `mounted()` function

**Comment by noso2k1** [comment]
@arttemiuss43 did you maybe place by mistake the `.env` file in the `src`folder? This happened to me and always got `undefined`.
Make sure you're placing the file in the root, where for example `gridsome.config.js` is.

**Comment by arttemiuss43** [comment]
Yeah. I placed .env file in the root of a project. This feature wasn't released yet when I faced this issue. It's released for now. So I will give it another shot. Thank you:)

**Pull request merged**
