### PR TITLE
Pages API

### PR DESCRIPTION
**Pull request by hjvedvik**
This PR adds a new API method called `createPages`. Use it to add custom pages or additional pages for store collections.

#### Basic example

```js
api.createPages(({ createPage }) => {
  createPage({
    path: '/custom-page',
    component: './src/templates/CustomPage.vue'
  })
})
```

#### Page context 

Each page can have a `context` property which will be available as variables in `page-query`. The context will also be available in Vue components as `$context`. This makes it possible to create pages with custom data without using GraphQL. If you only want the context to be available in `page-query`, set a `queryContext` property instead of `context`.

```js
api.createPages(({ createPage }) => {
  createPage({
    path: '/custom-page',
    component: './src/templates/CustomPage.vue',
    context /* or queryContext */: {
      customValue: '1'
    }
  })
})
```
```html
<template>
  <div>{{ $context.customValue }}</div>
</template>
```

#### Generating pages from GraphQL nodes

```js
api.createPages(async ({ graphql, createPage }) => {
  const { data } = await graphql('query { ... }')

  data.allProduct.edges.forEach(edge => {
    createPage({
      path: `${edge.node.path}/reviews`,
      component: './src/templates/ProductReviews.vue',
      context: {
        id: edge.node.id
      }
    })
  })
})
```
```graphql
query ProductReview ($id: String!) {
  product (id: $id) { ... }
}
```

### CODE REVIEW

**Comment by darkrubyist** [comment]
I tried the Create Pages API however, I got this error:

```

=> gridsome build
Gridsome v0.5.8

Initialize - 1.57s
TypeError: api.createPages is not a function
    at api.loadSource (~/gridsome.server.js:161:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

Will it be available only on Gridsome v0.6?

Thank you.

**Comment by hjvedvik** [comment]
Yes, it's not published to npm yet. We are preparing for 0.6 and writing documentation now, so it will hopefully be published within the next days :)

You can try the new API before it's published if you follow the [How to Contribute](https://github.com/gridsome/gridsome#how-to-contribute) guide.

**Comment by darkrubyist** [comment]
Thanks for the tip. I was waiting for createPage API for a long time. :)

Cheers!

**Comment by kamit-transient** [comment]
@hjvedvik I tried creating the page for `pages/Index.vue` to pass some context values for it, but I can see its not taking the `createPage(...)` , which I defined in gridsome.server.js for `path:"/"` and $context is empty.

I tied with below codes

```
 createPage({
    path: '/',
    component: './src/pages/Index.vue',
    context:{
myValue: 'Some Value'
}
  })
```

And Also by providing custom templates as well, like below:
```
 createPage({
    path: '/custom-page',
    component: './src/templates/Index.vue',
    context:{
              myValue: 'Some Value'
             }
  })

```

But Still same issue.

**Comment by mohsinxmushtaq** [comment]
Can we create layout page using the create page API ? im trying to create a global layout page also.

**Comment by hjvedvik** [comment]
@mohsinxmushtaq Not sure what you mean by a global layout page. But would a custom [`src/App.vue`](https://gridsome.org/docs/overriding-app/) work in your case? You can wrap `<router-view/>` in a layout in that component and it will be used for all pages on your site.

**Pull request merged**
