### PR TITLE
No fingerprints assets - Netlify and cache busting urls

### PR DESCRIPTION
**Pull request by igk1972**
This pull request adding the config option for disable the fingerprints in files. The files are obtained without changes.
**PR no effective without PR https://github.com/gridsome/gridsome/pull/839**

This is very necessary when the site has tens of thousands of HTML pages and as many json files.
Deployment time exceeds half an hour or more.

Netlfy_deploy

For support hosting like Netlify. 
https://www.netlify.com/blog/2017/02/23/better-living-through-caching/

Netlify processes every new file. It takes a lot of time.
Fingerprints are not needed for Netlify. The service runs on information in etag.
Also see https://github.com/gatsbyjs/gatsby/issues/11961#issuecomment-466029938

Probably not everyone needs this feature. But pull request allows now to solve the problem of deploying large sites on Netlify.

Gatsby has the same problems.
https://github.com/gatsbyjs/gatsby/issues/11961

### CODE REVIEW

**Comment by hjvedvik** [comment]
Thanks! I can review your PRs tomorrow :)

**Comment by igk1972** [comment]
Related  https://github.com/gridsome/gridsome/issues/584

**Comment by igk1972** [comment]
PR no effective without PR #839

**Comment by hjvedvik** [comment]
Thanks again for a good PR @igk1972 :) I have just one question. Can the option be `urlFingerprints: false` instead? We are trying to have a pattern for options where `false` will disable a default behavior.

**Comment by hjvedvik** [comment]
Or maybe `cacheBusting: false` because the JSON files actually have the hash inside the content instead of the URL. But it might not matter much :)

**Comment by igk1972** [comment]
It is not so important. 

Make (change) an option at your discretion, as you consider it better.

**Comment by igk1972** [comment]
cacheBusting is good :)

**Comment by hjvedvik** [comment]
Okay, then rename it to `cacheBusting` which defaults to `true` for the current behavior :)

**Comment by igk1972** [comment]
I did as needed, added a commit

**Comment by hjvedvik** [comment]
Thank you @igk1972 :)

**Comment by hacknug** [comment]
@hjvedvik any chance we can get something like this working for pages too?

**Pull request merged**
