### PR TITLE
transform-remark: front-matter parser config

### PR DESCRIPTION
**Pull request by eostrom**
Allow configuration of `gray-matter` from `gridsome.config.js`.

### CODE REVIEW

**Comment by eostrom** [comment]
Specifically I'm trying to use the `excerpt` and `excerpt_separator` options to parse Markdown posts from my old blog, but it seemed like the best approach was just to take an object of options and pass them through to `gray-matter`.

**Comment by roborich** [comment]
By the looks of it, this will solve the issue I created regarding remark.  #237  

I really think that the transform-remark plugin needs to either have `excerpt` functionality **OR** it needs to remove `excerpt` from the schema.  It is currently an unusable field in the GraphQL schema and is fairly confusing.

**Comment by robaxelsen** [comment]
Closing, as [PR with alternative solution](Prefixing the slugs which have leading numbers is safer, but results in uglier slugs.) has already been merged.

**Comment by eostrom** [comment]
@robaxelsen The PR you linked to was also closed without merging. Not saying that this one has to stay open, but has another solution for Markdown excerpts been implemented? It's not mentioned in the documentation.

**Comment by robaxelsen** [comment]
@eostrom Oh dang, my bad! Really sorry about that, and the confusion caused. Reopening!

**Comment by robaxelsen** [comment]
Oh wait.. Seems I assumed this commit had implemented this: https://github.com/gridsome/gridsome/pull/284/commits/9245c929b40c2693c9873e4a677ba1c1d89c179f

@hjvedvik is that the case?

@eostrom please test if you have the chance

**Comment by eostrom** [comment]
That commit brought my branch up to date with master (as of a week ago), but didn't merge my branch *into* master.

I can confirm that, with those updates, my branch still passes options to `gray-matter` the way I expect it to.

However, the excerpt is not parsed as Markdown. I can't remember whether this worked previously. I suspect not. (I've been going without excerpts for now.) Without Markdown parsing, this feature isn't useful to me personally. My use case is essentially #237.

At this point, I think the options are:

- Close this.
- Merge it, as the ability to configure `gray-matter` might be useful to someone.
- It looks to me like @hjvedvik has a plan for solving #237, which may make this moot.
- Given guidance on how the team thinks #237 should be solved, I'd be happy to help implement it.

I am content with any of these.

**Comment by hjvedvik** [comment]
@eostrom I think `gray-matter` only extracts the excerpts but we probably have to add an `excerpt` GraphQL field which parses the excerpt with the Remark parser. It would work pretty much like the `content` GraphQL field.

I wonder if it would be better to have an `excerpt` option instead of `grayMatter` and allow it to be a boolean or a function. Or what do you think?

**Comment by hjvedvik** [comment]
Thanks for the PR @eostrom :) And sorry for not merging it sooner... The plan has been to deprecate transformers and have a source plugin for each file type instead. But we haven't got the chance to start on them yet.

**Pull request merged**
