### PR TITLE
fix(source-ghost) add explicit schemas for ghost types

### PR DESCRIPTION
**Pull request by emilol**
Adds explicit schemas so that ghost fields on posts, pages, authors and tags that are empty can still be queried. Relates to #871.

### CODE REVIEW

**Comment by emilol** [comment]
Sorry about the cowboy commit! I've had some issues trying getting my project running from the projects folder as described in the readme (some packages in the project package.json seem to get skipped), so have been copying between separate projects to test.

Do you know of any other steps I need to take after pulling the project into ./projects and running yarn install? 

From ./projects, I'm running:

```
./gridsome/projects> git clone https://github.com/emilol/gridsome-starter-blumen
./gridsome/projects> cd gridsome-starter-blumen
./gridsome/projects/gridsome-starter-blumen> yarn install
./gridsome/projects/gridsome-starter-blumen> yarn develop

yarn run v1.17.3
$ gridsome develop
Error: Cannot find module 'gridsome-plugin-rss'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at resolvePluginEntries (.\gridsome\gridsome\lib\app\loadConfig.js:401:36)
    at plugins.map (.\gridsome\gridsome\lib\app\loadConfig.js:308:21)
    at Array.map (<anonymous>)
    at normalizePlugins (.\gridsome\gridsome\lib\app\loadConfig.js:301:18)
    at module.exports (.\gridsome\gridsome\lib\app\loadConfig.js:76:20)
    at new App (.\gridsome\gridsome\lib\app\App.js:23:42)
    at module.exports (.\gridsome\gridsome\lib\app\index.js:10:20)
    at module.exports (.\gridsome\gridsome\lib\develop.js:20:21)
```

**Comment by hjvedvik** [comment]
The commit is okay. The `yarn.lock` changes should have been merged with the PR which updated the `package.json` file, but it doesn't matter much :)

You can check if you have a version number in the `package.json` file in the project. I think Yarn ignores its dependencies if it doesn't have a version.

One more thing. Will the schemas work for the v2 API too? We could update to v3 as default and bump the version of this package to 0.3.

**Comment by emilol** [comment]
These schemas are working with v2 in that template above at the moment. 

I haven't tested with any other templates, but as far as I know that one's the one that queries the most fields so far. I'm all for changing the default.

**Comment by hjvedvik** [comment]
Okay, I'll change the default to v3. This PR looks good now. Thanks!

**Pull request merged**
