### PR TITLE
Add Support for Strapi Source to fetch Single Types

### PR DESCRIPTION
**Pull request by muellercornelius**
The Strapi CMS features Collection Types as well as single Types.

Those Commits enable the plugin to fetch the Single Types as well.

### CODE REVIEW

**Comment by Truemedia** [comment]
Code looks good at a glance will pull down and give a test over weekend. It's nice to see more people coding with strapi

**Comment by muellercornelius** [comment]
Thank you ;) Glad to hear that ;)

Yes I love Strapi ;)

**Comment by kendallroth** [comment]
Just curious whether there is anything outstanding for this merge request; starting a new project and hoping to use the single types.

**Comment by MrMacStripe** [comment]
Please merge this soon, without the powerful single types Strapi is restricted at the moment. Thanks in advance! @Truemedia

**Comment by Truemedia** [comment]
Sorry been really busy with other projects will take a look again this weekend

**Comment by Truemedia** [comment]
I have gridsome and strapi 3.0.1 setup on a fresh machine now (was setting up a raspberry pi to work on as my new workstation). Will be trying a few things to make sure can make the most of the stable release of strapi

**Comment by trubblebruin** [comment]
I'm working on a project which requires this; is anyone going to have time to review this PR soon and make a release please? No sweat if that won't be possible, I can always fork the repo and add these changes for the time being.

**Comment by hongweitang** [comment]
I see that there was 0.7.18 update. Is this going to be updated soon? I did some hotfixing but single types are totally missing to work with the current strapi version.

**Comment by Truemedia** [comment]
I have not been able to have the time I thought I would have to look at this due to problems in my personal and work life at the moment. Feel free for anyone else to pickup and have a look

**Comment by muellercornelius** [comment]
Could you please add a Label so somebody else will take a look at it?

**Comment by mitch104** [comment]
I'd also like to flag that single type support for Gridsome/Strapi is required on the project I'm working on, it would be very much appreciated if this could be resolved. Many thanks :+1:

**Comment by remi2j** [comment]
I work at Strapi and I'm building a Gridsome + Strapi starter. The lack of single types is a blocker.

This PR looks good to me and would close #1030.

Is there anyone other than @Truemedia who can get this merged?

**Comment by hjvedvik** [comment]
> Is there anyone other than @Truemedia who can get this merged?

@remi2j I'll merge it :)

**Pull request merged**
