### PR TITLE
feat(sass-resources-loader): add plugin for sass-resouces-loader setup

### LINKED ISSUE #55: Loading a global scss file
Hello all,

i try to load a global scss file using the sass-resources-loader package. 
I install this package and add a chainWebpack parameter to the config file: 
``chainWebpack: config => {
    config.module
      .rule('scss')
      .test(/\.scss$/)
        .use('sass-loader')
          .loader('sass-resources-loader')
          .options({
            resources: './scss/style.scss'
          });
  },``

It doesn't work and i don't really know if it's the best practice to add global scss vars to each components of my project so, any recommandation is welcome. 

Thank you for your help !

### PR DESCRIPTION
**Pull request by isoppp**
close #55 

inspired from [nuxt-sass-resources-loader](https://github.com/anteriovieira/nuxt-sass-resources-loader)

I will try to write document  after review if need it.

### CODE REVIEW

**Comment by mittalyashu** [comment]
Any progress over here?

**Comment by isoppp** [comment]
I think this PR will review after v0.5 release

**Comment by mittalyashu** [comment]
Really, that's sad 🤔

**Comment by hjvedvik** [comment]
@isoppp Sorry for not answering you sooner on this PR! The plugin looks great, but I think it would be better to maintain this kind of plugins outside this repository. We can create a repo for it on @gridsome  unless its easier for you to have it in on your account :)

**Comment by isoppp** [comment]
@hjvedvik 
Thank you for confirmation, I think too. :D
I'm going to go to serve this plugin in my account after couple days later.
Then I will be close this PR :)

**Comment by isoppp** [comment]
@hjvedvik @tomtev 
I published above [plugin](https://www.npmjs.com/package/gridsome-plugin-sass-resources-loader) :)
I  close this PR,  but probably we need to confirm #55 again.

**Comment by hjvedvik** [comment]
Thank you @isoppp :) And now it appears on the website too: https://gridsome.org/plugins/gridsome-plugin-sass-resources-loader

**Pull request closed without merging**
