### PR TITLE
feature: add option to toggle line numbers alongside code

### PR DESCRIPTION
**Pull request by Mini-ghost**
I add option `showLineNumbers: true` to display line numbers for `@gridsome/remark-prismjs`, and also tried to update the doc

this feature be mentioned at #1035  and #1048 

## Example:

set in `gridsome.config.js` 

```js
{
  remark: {
    plugins: [
      [
        require('./script/remark-prismjs'),
        {
          // display line numbers alongside code
          showLineNumbers: true
        }
      ]
    ]
  }
}
```
or if wish to only show line numbers on certain code blocks, leave false and use the `{ numberLines: true | number }` syntax below

````markdown
```js { numberLines: 21 }
interface IntersectionObserver {
  readonly root: Element | null;
  readonly rootMargin: string;
  readonly thresholds: ReadonlyArray<number>;
  disconnect(): void;
  observe(target: Element): void;
  takeRecords(): IntersectionObserverEntry[];
  unobserve(target: Element): void;
}
```
````

that will output this

image

### CODE REVIEW

**Comment by hjvedvik** [comment]
Thanks, @Mini-ghost! That's a feature that we've wanted for a while :) It seems to work well, but I think it maybe needs a minor change to work well with the default CSS. The `.line-numbers-rows` element should probably be a direct child of the `code` element instead.

And should we mention how to include the default CSS for line numbers in the readme?

```js
import 'prismjs/plugins/line-numbers/prism-line-numbers.css'
```

**Comment by Mini-ghost** [comment]
@hjvedvik Oops! I accidentally missed to mention how to include the default CSS for line numbers in the readme. I will add this paragraph.

About `.line-numbers-rows` element, now it is instead `pre` element (behind `code` element), like this:

```html
<pre class="language-typescript line-numbers">
  <code class="language-typescript">
    <!-- code contain  -->
  </code>
  <span class="line-numbers-rows" aria-hidden="true">
    <!-- span element of the line number -->
  </span>
</pre>
```

And your mean is this?

```html
<pre class="language-typescript line-numbers">
  <code class="language-typescript">
    <!-- code contain  -->
    <span class="line-numbers-rows" aria-hidden="true">
      <!-- span element of the line number -->
    </span>
  </code>
</pre>
```

**Comment by hjvedvik** [comment]
> And your mean is this?

Yes, that's right :) At least that's how the markup is in the [Line Numbers](https://prismjs.com/plugins/line-numbers/) plugin examples. And I could only get the default CSS to work with that markup.

And just one thought. Should we name the inline option `lineNumbers` instead? Just so it's more consistent with the global `showLineNumbers` option and the PrismJS plugin name.

```markdown
```js { lineNumbers: true }
interface IntersectionObserver {
  readonly root: Element | null;
```

**Comment by Mini-ghost** [comment]
> And just one thought. Should we name the inline option lineNumbers instead? Just so it's more consistent with the global showLineNumbers option and the PrismJS plugin name.

You are right. After I tried to use this option a many times, inconsistent naming is a little confusing for me , so I also think consistent naming is better.

I will adjust the structure of HTML elements, consistent option naming, and update the readme.

**Comment by hjvedvik** [comment]
The PR looks good now :) Thanks!

**Pull request merged**
