### PR TITLE
Added key to viewport

### PR DESCRIPTION
**Pull request by physcocode**
I wanted to override default viewport information, but I could not.

### CODE REVIEW

**Comment by physcocode** [comment]
Also siteDescription do not work for me, does it have something to do with 
description: config.siteDescription not present in this file ?

I encourage siteDescription to be mandatory to have a higher SEO score

**Comment by physcocode** [comment]
oops seems like #70  is yet to be merged

**Comment by tomtev** [comment]
What does key: 'viewport' do? Also, I think you missed a comma :)

**Comment by physcocode** [comment]
@tomtev well actually I wanted to change the viewport meta to content: 'width=device-width, initial-scale=1, shrink-to-fit' but I could not override this because there was no 'key' set

**Comment by tomtev** [comment]
Ah, nice. Maybe we should add a key to charset also? 

We should probably also make a 'head' option for gridsome.config.js so we could add for example:
```
head: {
  { key:'viewport', name: 'viewport', content: 'width=device-width' },
}
```

**Comment by physcocode** [comment]
@tomtev @hjvedvik eagerly waiting for #70 and this to be merged in the core :)

**Comment by tomtev** [comment]
Yes, its easy when you know how to do it :) Was just thinking its simpler for users to read config docs and see that there is are options for adding stuff to head. But we have a good documentation here https://gridsome.org/docs/head so I agree it's probably not needed.

**Pull request merged**
