### PR TITLE
API for customizing the GraphQL schema

### PR DESCRIPTION
**Pull request by hjvedvik**
Gridsome generates a GraphQL schema based on your data. That's great for simple projects but will often lead to errors with for example missing fields because content has been removed in the CMS. This API will let plugins define their own schema types to have consistent fields and types. You can also use the API in your `gridsome.server.js` file.

#### Example usage

```js
module.exports = function (api) {
  api.loadSource(({ addSchemaTypes }) => {
    addSchemaTypes(`
      type Post implements Node {
        title: String
        publishedAt: Date # date field with format argument
        author: Author # reference an Author content type by id
        tag: Tag @reference(by: "slug") # reference a Tag type by slug
        camelCased: String @proxy(from:"snake_cased") # get value from another field
      }
    `)
  })
}
```

Gridsome will not add fields to custom schema types by default. Add a `@infer` directive to include undefined schema fields from the nodes: `type Post implements Node @infer { ... }`. But it's recommended to define all fields.

Schema types can also be added with code:

```js
module.exports = function (api) {
  api.loadSource(({ addSchemaTypes, schema }) => {
    addSchemaTypes([
      schema.createObjectType({
        name: 'Post',
        fields: {
          title: 'String',
          publishedAt: 'Date',
          author: 'Author',
          tag: {
            type: 'Tag',
            extensions: {
              reference: {
                by: 'slug'
              }
            }
          }
        }
      })
    ])
  })
}
```

#### Adding resolvers

You can add resolvers by using `addSchemaTypes` with `schema.createObjectType`. But a `addSchemaResolvers` method will let you add resolver for SDL types or override existing resolvers.

```js
module.exports = function (api) {
  api.loadSource(({ addSchemaResolvers }) => {
    addSchemaResolvers({
      Post: {
        title: {
          type: 'String',
          args: {
            uppercase: 'Boolean'
          },
          resolve (node, args) {
            return args.uppercase ? node.title.toUpperCase() : node.title
          }
        }
      }
    })
  })
}
```

#### Changes

- Removes deprecated `node._id` and `node.fields` fields.
- Query variables for node ids must be `ID` instead of `String`. 
 *Gridsome will attempt to fix this automatically, but it's recommended to change the query.*
- Camelcase the collection field name when not in pascal case. 
 *A `test_post` type name became `alltest_post`, but will now be `allTestPost` instead. The old field name still exists but is deprecated.*

### CODE REVIEW

**Comment by martifenosa** [comment]
Is this scheduled to merge? We all are really hyped for it in our office. It should be the solution to most of the issues we have in our two Gridsome projects.

**Comment by hjvedvik** [comment]
@martifenosa Yes, we'll try to merge this next week :)

**Comment by freshyill** [comment]
Any chance this is coming soon?

**Comment by hjvedvik** [comment]
@freshyill Didn't get a chance to finish this before the summer vacation here in Norway, unfortunately. But we are back now and I'm working on the next release these days. So we'll hopefully merge this pretty soon :)

**Comment by mattbrailsford** [comment]
Great to see this get merged in. Is there any advice/docs/tests for how to get started trying it out?

**Comment by hjvedvik** [comment]
@mattbrailsford Would be great if you are able to test this feature before we publish it :) You can follow the [contribution guide](https://github.com/gridsome/gridsome#how-to-contribute) to run your project using packages from the master branch. We are still working on the documentation [here](https://deploy-preview-239--gridsome-org-live.netlify.com/docs/schema-api/).

**Comment by mattbrailsford** [comment]
@hjvedvik no problem. I'll see what I can get working. Docs look a great starting point 👍

**Comment by mattbrailsford** [comment]
@hjvedvik just to let you know, I had a specific use case for this, being able to define a custom API and then to create content types that implement that interface and I can confirm I managed to achieve this with the new API changes.

I'll try and take a look at some more advanced usages, as I would like to load all my content types from an endpoint (I'm currently inferring them all), so will let you know how that goes.

**Comment by hjvedvik** [comment]
Thanks for testing @martifenosa :) And glad you achieved what you wanted with the new API. I think the master branch is ready for publishing now. Did you manage to test more advanced use cases?

**Comment by martifenosa** [comment]
I think @mattbrailsford did the testing :P

**Comment by hjvedvik** [comment]
Ups, you're right @martifenosa :P

**Pull request merged**
